# Generated by Django 6.0.3 on 2026-03-12 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_estudio', models.CharField(max_length=255, verbose_name='Nombre del Estudio')),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('fresa', 'Fresa'), ('cacao', 'Cacao'), ('manzana', 'Manzana'), ('tomate', 'Tomate'), ('cafe', 'Café'), ('platano', 'Plátano'), ('otro', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('entrenamiento', 'En Entrenamiento')], default='activo', max_length=20)),
                ('archivo_modelo', models.FileField(help_text='Sube el archivo de tu modelo entrenado (formato .onnx recomendado)', upload_to='modelos_ml/', verbose_name='Archivo del Modelo (.onnx)')),
                ('documento_estudio', models.FileField(blank=True, help_text='Documento PDF con la investigación o estudio relacionado', null=True, upload_to='estudios_pdf/', verbose_name='Documento del Estudio (PDF)')),
                ('precision', models.DecimalField(blank=True, decimal_places=2, help_text='Precisión del modelo en porcentaje (ej: 95.87)', max_digits=5, null=True, verbose_name='Precisión (%)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_ml', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo ML',
                'verbose_name_plural': 'Modelos ML',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
