# Generated by Django 6.0.3 on 2026-03-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_modeloml'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
