# Generated by Django 6.0.3 on 2026-03-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloml',
            name='es_rgb',
            field=models.BooleanField(default=False, help_text='Marca esta opción si el modelo fue entrenado con imágenes a color. Déjalo vacío si es en escala de grises.', verbose_name='¿Es RGB (A color)?'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='img_height',
            field=models.IntegerField(default=28, help_text='Alto esperado de la imagen por el modelo ONNX (ej: 28, 224).', verbose_name='Alto de Entrada (px)'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='img_width',
            field=models.IntegerField(default=28, help_text='Ancho esperado de la imagen por el modelo ONNX (ej: 28, 224).', verbose_name='Ancho de Entrada (px)'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='invertir_colores',
            field=models.BooleanField(default=False, help_text='Ideal para modelos como MNIST que esperan trazos blancos sobre fondo negro.', verbose_name='¿Invertir Colores?'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='nombres_clases',
            field=models.TextField(blank=True, help_text='Nombres separados por comas. Ej: "Manzana Sana,Manzana Enferma". Convierte el resultado numérico en texto legible.', null=True, verbose_name='Nombres de las Clases'),
        ),
    ]
