# Generated by Django 6.0.3 on 2026-03-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_modeloml_es_rgb_modeloml_img_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloml',
            name='archivo_modelo',
            field=models.FileField(help_text='Sube el archivo de tu modelo entrenado (formatos aceptados: .onnx, .pkl)', upload_to='modelos_ml/', verbose_name='Archivo del Modelo (.onnx, .pkl)'),
        ),
    ]
