# Generated by Django 6.0.3 on 2026-03-30 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_categoria_alter_modeloml_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='historial_imagenes/', verbose_name='Imagen de entrada')),
                ('ubicacion', models.CharField(blank=True, default='', max_length=255, verbose_name='Ubicación')),
                ('resultado', models.TextField(blank=True, default='', verbose_name='Resultado')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ejecución')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_ejecuciones', to='app.modeloml', verbose_name='Modelo usado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_ejecuciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Ejecución',
                'verbose_name_plural': 'Historial de Ejecuciones',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
