"""
Django settings for proyecto project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os  # Importa el módulo os para interactuar con el sistema operativo, especialmente para manejar rutas y variables de entorno
from os import getenv  # Importa la función getenv para acceder a variables de entorno del sistema
from dotenv import load_dotenv  # Importa load_dotenv, que permite cargar automáticamente las variables desde un archivo .env
load_dotenv()  # Carga las variables de entorno definidas en el archivo .env ubicado en la raíz del proyecto
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zyusna=9#@7djxnme-yo07_k&!)o0i($#4(i!sel-k^kxsq_b8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = ['crudv2-bcena2gzdbfhbfc2.mexicocentral-01.azurewebsites.net']
# CSRF_TRUSTED_ORIGINS = ['https://*']
CSRF_TRUSTED_ORIGINS = [os.getenv("DOMINIO")]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Agregar esta línea
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv("DBNAME"),
#         'HOST': os.getenv("DBHOST"),
#         'USER': os.getenv("DBUSER"),
#         'PASSWORD': os.getenv("DBPASSWORD"),
#         'PORT': os.getenv("DBPORT"),
#         'OPTIONS': {
#             'sslmode': 'require',
#         },
#     }
# }

# # # Integrando Azure Blob Storage

# Configuración para integrar Azure Blob Storage en un proyecto de Django.
STORAGES = {
    # Configuración para el almacenamiento predeterminado.
    "default": {
        # Especifica el backend utilizado para manejar el almacenamiento predeterminado.
        # En este caso, se utiliza el backend de Azure Storage.
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        # Opciones adicionales para personalizar el comportamiento del almacenamiento.
        "OPTIONS": {
            # Tiempo de espera (en segundos) para las conexiones al almacenamiento de Azure.
            'timeout': 20,
            # Tiempo (en segundos) durante el cual una URL firmada será válida.
            'expiration_secs': 500,
        },
    },
    # Configuración para el almacenamiento de archivos estáticos.
    "staticfiles": {
        # Especifica el backend utilizado para manejar los archivos estáticos.
        # En este caso, se utiliza el almacenamiento predeterminado para archivos estáticos de Django.
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# # -----------------------------------------
# TO-DO add the static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# URL para acceder a los archivos estáticos
STATIC_URL = '/static/'

# Directorio donde guardarás los archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / "app" / "static",
]





# Media files and storage block (Azure Blob Storage placeholder)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AZURE_CONTAINER = os.getenv("AZURE_CONTAINER")
AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY =os.getenv("AZURE_ACCOUNT_KEY")

# ----------------------------------------------------
# CONFIGURACIÓN DE CORREOS PARA 2FA (OTP)
# ----------------------------------------------------
if os.getenv('EMAIL_HOST_USER'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    # Para la etapa de desarrollo, si no hay credenciales, veremos los códigos en la consola.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'no-reply@proyectoml.local'

